### ISSUE TITLE
Hardcoded path?

### ISSUE THREAD

**Issue by arno481** [Erik-Lamers1/vnet-manager#10]
Hi
the code seems to assume VNet-Manager is always installed in the current user's home directory. Which it is not in my case...

````
root@inr2020:/home/arno/co/github/vnet-manager# vnet-manager create config/example.yaml
2020-10-30 11:47:54,812 [vnet_manager.utils.files] [ERROR] File /root/vnet-manager/config/defaults.yaml does not exist
````

The joy of having actual users testing your software ;o)

CU,
           Arno

**Comment by arno481** [comment]
I should RTFM apparently, but I'd prefer the vnet-manager script to determine where it is in the filesystem (via sys.argv[0]) and assume its files are stored in that location as well.

My $0.02,
           Arno

**Comment by Erik-Lamers1** [comment]
Hi Arno, 

Yeah, you are correct VNet-manager assumes `~/vnet-manager/config/defaults.yaml` by default. 
If this file is located somewhere else you can use the `VNET_DEFAULT_CONFIG_PATH` environment variable to set the path.

So, in your case this will be;
```
export VNET_DEFAULT_CONFIG_PATH=/home/arno/co/github/vnet-manager/config/defaults.yaml
```

And yes I do think I should make this easier to configure. On the other hand, I'm thinking of phasing out the need for defaults.yaml entirely. But this is something for a later release.
