### ISSUE TITLE
Host type has IPv4 forwarding enabled

### ISSUE THREAD

**Issue by arno481** [Erik-Lamers1/vnet-manager#11]
Hi

machines of type "host" have IPv4 forwarding enabled (IPv6 is off):
````
root@host1:~# cat /proc/sys/net/ipv4/ip_forward
1
root@host1:~# cat /proc/sys/net/ipv6/conf/all/forwarding 
0
````
I'd prefer it "Off" by default. /etc/sysctl.conf also suggests it is off:
````
root@host1:~# grep forward /etc/sysctl.conf 
# Uncomment the next line to enable packet forwarding for IPv4
#net.ipv4.ip_forward=1
# Uncomment the next line to enable packet forwarding for IPv6
#net.ipv6.conf.all.forwarding=1
````

**Comment by Erik-Lamers1** [comment]
I agree that IP forwarding should be disabled by default on hosts. The weird thing is that I can't seem to locate where this setting is actually enabled. So to tackle this I made https://github.com/Erik-Lamers1/vnet-manager/pull/12 to explicitly disable IP forwarding on hosts.
