### ISSUE TITLE
Feature request: lxd init using --preseed / YAML file

### ISSUE THREAD

**Issue by arno481** [Erik-Lamers1/vnet-manager#13]
Hi

I think it is more robust to do an lxd init using an YAML file as input, as enabled via --preseed (and using --dump) than the echo "\n" | lxd init construction.

See e.g.
 https://discuss.linuxcontainers.org/t/how-to-get-the-full-configuration-to-use-it-with-lxd-init-preseed/3333/5

**Comment by Erik-Lamers1** [comment]
Closing in favour of https://github.com/Erik-Lamers1/vnet-manager/issues/16
