### ISSUE TITLE
Feature request: rename --no-hosts to --no-etc-hosts

### ISSUE THREAD

**Issue by arno481** [Erik-Lamers1/vnet-manager#17]
For clarity ;o)

**Comment by Erik-Lamers1** [comment]
I'm personally in favour of keeping the command line options as short as possible. More typing means less happy developers in my experience. And I think the feature is clearly documented;
```
root@toulouse:~# vnet-manager --help 2>&1 | grep hosts
  -nh, --no-hosts       Disable creation of /etc/hosts
```

I'm rejecting this request for now. If you feel like this is a good option 👍 it and I'll consider reopening it.
